first_project/first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('',views.index,name="index"),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name="logout"),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# CREATE SOME TEST DATA WITH SOME SHELL COMMANDS:

# python manage.py shell

# from first_app.models import Topic
# print(Topic.objects.all())
# t = Topic(top_name="Social Network")
# t.save()
# print(Topic.objects.all())
# quit()

# Create your models here.
# class Topic(models.Model):
#     top_name = models.CharField(max_length=264,unique=True)

#     def __str__(self):
#         return self.top_name

# class Webpage(models.Model):
#     topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
#     name = models.CharField(max_length=264,unique=True)
#     url = models.URLField(unique=True)

#     def __str__(self):
#         return self.name

# class AccessRecord(models.Model):
#     name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
#     date = models.DateField()

#     def __str__(self):
#         return str(self.date)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #class object attributes to be added

    portfolio = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo



# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)

#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verify_email']

#         if email != vmail:
#             raise forms.ValidationError("MAKE SURE EMAILS MATCH!")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from .forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.

# def index(request):
#     return HttpResponse("Hello World!")

# Our original index view function
# corresponds to indexOLD.html (rename it to index.html to use it!)



def index(request):
    return render(request,'first_app/index_4.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            
            user = user_form.save()

            
            user.set_password(user.password)

            
            user.save()

            
            profile = profile_form.save(commit=False) 
            profile.user = user
            profile.save()

            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'first_app/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
    


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:

                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                print("Account Not Active!")
        else:
            return HttpResponse("invalid login details please go to login page and try again")
    
    else:
        return render(request,'first_app/login.html',{})
    


first_project/first_app/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css"%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DMS</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'first_app:register' %}">Register</a>

        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'first_app:login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

first_project/first_app/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Forms</title>
</head>
<body>
    <h1>Fill out the form!</h1>
    <div class="container">
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>

first_project/first_app/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{% static "first_app/css/mystyle.css" %}"/>
  </head>
  <body>
    <h1>Hi, welcome to Django Level Two!</h1>
    <h2>Here are your access records:</h2>
    <div class="djangtwo">
      {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Accessed</th>
            </thead>

            {% for acc in access_records %}
              <tr>
                <td>{{ acc.name }}</td>
                <td>{{ acc.date }}</td>
              </tr>
            {% endfor %}
        </table>

      {% else %}
        <p>No Access Records. Table Not Created.</p>
      {% endif %}
    </div>

  </body>
</html>

first_project/first_app/templates/first_app/indexOLD.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>First App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to home page</h1>
        <h2>Go to /formpage to fill out the form</h2>
      </div>
    </div>
  </body>
</html>

first_project/first_app/templates/first_app/index_4.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to our home page</h1>
        {% if user.is_authenticated %}
        <p>The site is not ready yet! We will let you know when it is</p>
        {% else %}
        {% endif %}
    </div>
    {% endblock %}

first_project/first_app/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Login Here</h1>
        <form action="{%url 'first_app:login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter your name here">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

first_project/first_app/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
  <h1>WELCOME TO OTHER</h1>
  {% endblock %}

first_project/first_app/templates/first_app/register.html
{% extends "first_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

first_project/first_app/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>THIS IS RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'first_app:other' %}">LINK to other</a>
    <a href="{% url 'admin:index' %}">LINK to admin</a>
    <a href="{% url 'first_app:index' %}">Link to INDEX</a>
</body>
</html>